# Generated by Django 4.2 on 2023-04-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_box_storage_subscription_box_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='main_site.storage', verbose_name='Хранилище'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main_site.box', verbose_name='Бокс'),
        ),
    ]
