# Generated by Django 4.2 on 2023-04-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_box_storage_alter_subscription_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='temperature',
            field=models.DecimalField(decimal_places=5, default=10, max_digits=10, verbose_name='Температура на складе'),
            preserve_default=False,
        ),
    ]
