# Generated by Django 4.2 on 2023-04-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_storage_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='rental_price',
            field=models.DecimalField(decimal_places=5, default=100, max_digits=10, verbose_name='Цена аренды'),
            preserve_default=False,
        ),
    ]
