# Generated by Django 4.2 on 2023-04-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_alter_box_height_alter_box_length_alter_box_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='large_photo',
            field=models.ImageField(blank=True, default='image2.png', upload_to='', verbose_name='Большое фото'),
        ),
        migrations.AddField(
            model_name='storage',
            name='small_photo',
            field=models.ImageField(blank=True, default='image9.png', upload_to='', verbose_name='Маленькое фото'),
        ),
    ]
