# Generated by Django 4.2 on 2023-04-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_remove_storage_large_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
    ]
