# Generated by Django 4.2 on 2023-04-22 10:51
import random
import string

from django.db import migrations


def create_boxes(apps, schema_editor):
    letters = string.ascii_lowercase
    Storage = apps.get_model('main_site', 'Storage')
    Box = apps.get_model('main_site', 'Box')
    storages = Storage.objects.all()
    for storage in storages:
        for boxes_quantity in range(5):
            random_string = ''.join(random.choice(letters) for i in range(2)).upper()
            Box.objects.get_or_create(
                storage=storage,
                number=f'{random_string}-{random.randint(1000, 9999)}',
                width=("%.2f" % random.uniform(0.0, 5.0)),
                length=("%.2f" % random.uniform(0.0, 5.0)),
                height=("%.2f" % random.uniform(0.0, 5.0)),
                floor=random.randint(1, 5)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_user_phonenumber'),
    ]

    operations = [
        migrations.RunPython(create_boxes)
    ]
