# Generated by Django 4.2 on 2023-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0016_auto_20230422_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
