# Generated by Django 4.2 on 2023-04-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_alter_storage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='latest_notification',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего уведомления'),
        ),
    ]
